### ISSUE TITLE
第三步执行不了

### ISSUE THREAD

**Issue by sunbos** [stevenjoezhang/bilibili-downloader#1]
到了第三步npm install，就会-bash: npm: command not found

**Comment by stevenjoezhang** [comment]
先试试用包管理工具或者从 https://nodejs.org/en/ 下载安装node和npm

**Comment by sunbos** [comment]
sunbos-MBP:mimi-downloader sunbo$ npm install

> electron@3.1.1 postinstall /Users/sunbo/mimi-downloader/node_modules/electron
> node install.js

Downloading tmp-1650-0-electron-v3.1.1-darwin-x64.zip
Error: read ECONNRESET
/Users/sunbo/mimi-downloader/node_modules/electron/install.js:49
  throw err
  ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@3.1.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@3.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sunbo/.npm/_logs/2019-01-20T13_33_53_037Z-debug.log

**Comment by sunbos** [comment]
Downloading tmp-1737-0-electron-v3.1.1-darwin-x64.zip
[>                                            ] 0.0% of 50.21 MB (4.36 kB/s)
一直卡在这个地方

**Comment by stevenjoezhang** [comment]
这个应该是被墙了..你可以挂个代理看看

**Comment by stevenjoezhang** [comment]
Electron 7 似乎不方便挂代理下载，退回到 6.1.5 版本了。
