### ISSUE TITLE
下载Mp4

### ISSUE THREAD

**Issue by plybb** [stevenjoezhang/bilibili-downloader#13]
下载MP4，如何操作呢？谢谢

**Comment by stevenjoezhang** [comment]
可以下载 flv 后，使用 ffmpeg 等工具转码。B站通过 iframe 播放的视频是 mp4 格式，但分辨率似乎最高只有 360P。

**Comment by plybb** [comment]
ffmpeg就很方便了，谢谢。大会员下载1080+需要手动导入cookies？这一操作如何实现呢

**Comment by stevenjoezhang** [comment]
导入 cookies 我还没写，可以试试这个： https://github.com/kamikat/bilibili-get

**Comment by plybb** [comment]
@stevenjoezhang 点赞！！
