### ISSUE TITLE
大佬好，请问多P下载的参数问题

### ISSUE THREAD

**Issue by supuwoerc** [stevenjoezhang/bilibili-downloader#20]
RT，小弟我来找轮子找到大佬你的工具，但是我的目的是下载超多分P教程，大概1000P，请问参数怎么传呢？我可以写个for循环输出字符串，请大佬告知参数的拼接方式 =。=

**Comment by stevenjoezhang** [comment]
你好，可以参考这个 Fork 的版本 https://github.com/Borber/bilibili-downloader

**Comment by stevenjoezhang** [comment]
或者基于 you-get 这样的命令行工具进行开发，似乎不难实现
