### ISSUE TITLE
下载问题 目录或文件 不存在

### ISSUE THREAD

**Issue by Borber** [stevenjoezhang/bilibili-downloader#22]
![image](https://user-images.githubusercontent.com/30563826/78580531-19e9bc80-7865-11ea-83b7-74cdc6913825.png)

不知是何缘故

**Comment by stevenjoezhang** [comment]
我不确定是不是某些特殊字符在 Windows 下导致了问题。能否把文件名修改为英文/数字试试？

**Comment by Borber** [comment]
> 我不确定是不是某些特殊字符在 Windows 下导致了问题。能否把文件名修改为英文/数字试试？

好的 我尝试一下

**Comment by Borber** [comment]
> 我不确定是不是某些特殊字符在 Windows 下导致了问题。能否把文件名修改为英文/数字试试？

OK 是的 更改名字就可以了 以及想反应一下 好像 浏览来选择下载目录 输入框没有改变

**Comment by stevenjoezhang** [comment]
好的，谢谢反馈。我待会确认一下如何修复。

**Comment by stevenjoezhang** [comment]
> 浏览来选择下载目录 输入框没有改变

这个问题定位到了，有个 API 被弃用了，我这边没更新。

> 是不是某些特殊字符在 Windows 下导致了问题。

测试了一下，应该是由于 Windows 不允许文件名中出现 `?` `\` 这样的字符导致的。

**Comment by Borber** [comment]
> > 浏览来选择下载目录 输入框没有改变
> 
> 这个问题定位到了，有个 API 被弃用了，我这边没更新。
> 
> > 是不是某些特殊字符在 Windows 下导致了问题。
> 
> 测试了一下，应该是由于 Windows 不允许文件名中出现 `?` `\` 这样的字符导致的。

好的 感谢

**Comment by Borber** [comment]
> > 浏览来选择下载目录 输入框没有改变
> 
> 这个问题定位到了，有个 API 被弃用了，我这边没更新。
> 
> > 是不是某些特殊字符在 Windows 下导致了问题。
> 
> 测试了一下，应该是由于 Windows 不允许文件名中出现 `?` `\` 这样的字符导致的。

![image](https://user-images.githubusercontent.com/30563826/78763466-c20f9a80-79b7-11ea-8246-c8198ada60d0.png)

正在分析 你的代码 想要魔改一下 哈哈哈哈

**Comment by stevenjoezhang** [comment]
我的代码写的比较随意，GitHub 上 Star 数多了才有动力重构 😂
可以参考这几个 Python 写的，功能比较全：
https://github.com/stevenjoezhang/bilibili-downloader#相关项目

**Comment by Borber** [comment]
> 我的代码写的比较随意，GitHub 上 Star 数多了才有动力重构 😂
> 可以参考这几个 Python 写的，功能比较全：
> [https://github.com/stevenjoezhang/bilibili-downloader#相关项目](https://github.com/stevenjoezhang/bilibili-downloader#%E7%9B%B8%E5%85%B3%E9%A1%B9%E7%9B%AE)

我是想打包成 桌面应用 选来选去还是觉得electron 是最佳选择 前面一直在弄这个相关 看到你的项目觉得完成度已经不错了

**Comment by stevenjoezhang** [comment]
这个 Bug 应该修复了： https://github.com/stevenjoezhang/bilibili-downloader/commit/d9462c345a7dc699a37c5b8644201a25965fce4b
有其他问题欢迎继续讨论～
