### ISSUE TITLE
下载视频卡主

### ISSUE THREAD

**Issue by gujiwuqing** [stevenjoezhang/bilibili-downloader#64]
hello 想咨询下载视频的时候会卡主 请问什么情况
<img width="636" alt="image" src="https://user-images.githubusercontent.com/44566835/166186758-627c5fd1-593a-4be6-8b54-ddaeb914dc96.png">

如何解决 求解 谢谢

**Comment by stevenjoezhang** [comment]
我试了下可以正常下载，你看看是不是网络问题

**Comment by stevenjoezhang** [comment]
最新版加上登录功能了，欢迎试用： https://github.com/stevenjoezhang/bilibili-downloader/commit/09c1a2c5a91620c9f205b3ffb46da04d41a597e8
