### ISSUE TITLE
希望增加一个可以选择下载什么分辨率的功能

### ISSUE THREAD

**Issue by qdhonker** [stevenjoezhang/bilibili-downloader#73]
希望增加一个可以选择下载什么分辨率的功能

**Comment by stevenjoezhang** [comment]
可能加不了，b站限制变严格了，现在新的视频必须登录才能下载高清的

**Comment by qdhonker** [comment]
登陆功能之前有做过吗

**Comment by stevenjoezhang** [comment]
最新版加上登录功能了，欢迎试用： https://github.com/stevenjoezhang/bilibili-downloader/commit/09c1a2c5a91620c9f205b3ffb46da04d41a597e8
